# -*- coding: utf-8 -*-
"""Largest of three.ipy

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Q-wfI20vurAac3Ig5SNN8R3VQqYM7eMi
"""

import streamlit as st

num1 = st.number_input("Enter the first number")
num2 = st.number_input("Enter the second number")
num3 = st.number_input("Enter the third number")


# Python program to find greatest of three numbers using function

def findLargest(num1, num2, num3): #user-defined function
    # find largest numbers
    if (num1 >= num2) and (num1 >= num3):
        largest = num1
    elif (num2 >= num1) and (num2 >= num3):
        largest = num2
    else:
        largest = num3
    return largest #return value

# function call
maximum = findLargest(num1, num2, num3)

# display result
st.write("The largest number is ", maximum)
